[Fix] - OpenData Failing Job
OpenSourcePolitics/decidim-tou pull request #118
Opened 2023-03-17 09:11 UTC by AyakorK

#### 🎩 Description

This PR is made to fix the OpenDataJob that was crashing if the author of a proposal was an organization because of the overriding of the serializer.

### 📌 Related Issues

Related to [Notion](https://www.notion.so/opensourcepolitics/Toulouse-OpenDataJob-fails-and-blocks-exports-queue-f926e55a82e347eba4cd0dd5f29dce89?pvs=4)

### 📝 What has been done

- Fix Serializer
- Change queue of the job
- Add some specs
- Rewrite the cron to match the format of a normal cron task

2023-03-17 09:34 UTC, paulinebessoles approved these changes

2023-03-17 09:53 UTC, Quentinchampenois requested changes
Nice work, I just have a few changes suggestions

2023-03-17 09:53 UTC, Quentinchampenois commented on lib/extends/exporters/proposal_serializer.rb
> +    phone_number(proposal.creator_identity.try(:user_id)) || ""
```suggestion
    return "" if proposal.creator_identity.try(:user_id).blank?

    phone_number(proposal.creator_identity.try(:user_id))
```

2023-03-17 09:53 UTC, Quentinchampenois commented on lib/extends/exporters/proposal_serializer.rb
> +    return "" if user_id.blank?
If we add condition in `create_phon_number`, this guard clause is no longer needed

2023-03-22 11:29 UTC, Quentinchampenois requested changes
I come back on the suggestion I made to create the queue `low`,
 I will fix it today on this PR, and reduce the retry count from default (25) to 2 because it is a scheduled job

2023-03-22 11:48 UTC, Quentinchampenois commented
I keep the `low` queue because main issue was OpenDataJob was blocking the whole queue and admins can't receive exports from application

2023-03-22 11:49 UTC, Quentinchampenois approved these changes
LGTM

2023-03-22 14:13 UTC, merged