[Fix] Fix global errors
OpenSourcePolitics/decidim-tou pull request #147
Opened 2023-09-13 09:43 UTC by AyakorK

#### :tophat: Description
This PR has been made to fix few errors that we encountered in the production of Toulouse after getting to IndieHosters

#### :pushpin: Related Issues
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Recette-IH-ef758db211ae49da90645198d90983ed?pvs=4)

#### Tasks
- [x] Add configs
- [x] Override graphical files to change method
- [ ] Extends a cell to add a new method (May won't work we need to try this in production or with a dump)

2023-09-13 09:57 UTC, paulinebessoles requested changes
Thank you @AyakorK ! Could you keep just the config/sidekiq.yml, config/secrets.yml and yarn.lock files for this PR? I think that it will be enough to fix the search issue

2023-09-13 10:18 UTC, paulinebessoles approved these changes

2023-09-13 15:07 UTC, Quentinchampenois requested changes
Can you add the related spec system for the `posts` partial please ? 

Otherwise it looks good to me

2023-09-14 12:15 UTC, paulinebessoles approved these changes

2023-10-11 14:43 UTC, paulinebessoles approved these changes

2023-10-11 14:43 UTC, merged