feat: Add SMS Gateway Service
OpenSourcePolitics/decidim-tou pull request #193
Opened 2024-04-16 16:17 UTC by Quentinchampenois

#### :tophat: Description
*Please describe your pull request.*

Add EtoileDiese SMS provider

#### :pushpin: Related Issues
*Link your PR to an issue*
- [Notion card](https://www.notion.so/opensourcepolitics/Half-sign-up-avec-toile-Di-se-15e620cdd3b0489592640c8f1efccef0?pvs=4)

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Run application with env var `SMS_GATEWAY_USERNAME=<username> SMS_GATEWAY_PASSWORD=<pwd> bundle exec rails s`
* Go to budget
* Try to vote
* Enter your phone number
* receive SMS

2024-04-17 11:44 UTC, AyakorK approved these changes
Looks good but still may be a bit useless to keep the logger into the `sms_gateway_service.rb` as it is certainly useful as a debug but not mandatory at all.

2024-04-17 13:16 UTC, AyakorK requested changes

2024-04-17 13:16 UTC, AyakorK commented on app/services/decidim/sms_gateway_service.rb
> +      Rails.logger.info("#########################################################")
We may get rid of those loggers as it seems pretty useless except for debugging

2024-04-30 06:59 UTC, luciegrau approved these changes

2024-04-30 06:59 UTC, merged