Fix delete image with apostrophe in its name in admin process
OpenSourcePolitics/decidim-tou pull request #227
Opened 2024-06-28 13:38 UTC by Stef-Rousset

#### :tophat: Description
As an admin, I should be able to delete an image with an apostrophe in its name in a participatory process.

#### :pushpin: Related Issues
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=8933583982234acdb3cfa13ad47477c5&pm=c)
- backport of https://github.com/decidim/decidim/pull/11731
#### Testing
1. As an admin, go to a participatory process
2. Take the image linked to the PR and change its name for a name including an apostrophe (like "image d'aujourd'hui")
3. Edit the process and add the image below, then click on save, and update the process
4. Go again on the banner image, click on replace, then click on remove, save and update.
5. See that you have deleted the image

![bandeau d'arc bis](https://github.com/OpenSourcePolitics/decidim-tou/assets/61418966/6feb0b88-2de9-483a-909c-0ff01416e158)

2024-07-03 09:35 UTC, luciegrau requested changes
Hi @Stef-Rousset ! I tested locally and unfortunately the PR does not pass the product review 😞 . When I add a banner image with an apostrophe in its name, I can't delete it and add a new banner image. Below is a screencast showing the problem : 

https://github.com/OpenSourcePolitics/decidim-tou/assets/87868063/a8e495f6-28fa-4e26-8885-7253e96427c5

2024-07-03 12:36 UTC, BarbaraOliveira13 approved these changes
I ran It, it works here

2024-07-04 11:58 UTC, luciegrau approved these changes

2024-07-15 07:49 UTC, luciegrau approved these changes

2024-07-15 14:08 UTC, BarbaraOliveira13 approved these changes
Re-run and still works 🎉

2024-07-29 08:28 UTC, Quentinchampenois approved these changes

2024-07-29 08:28 UTC, merged